# Changing server port
server:
  port: 8082

# Configuration for microservice service registry (eureka server)
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # by default it will be true even if don't write this line
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka

spring:

# Configuration for Application name (this name will be displayed in microservice's eureka server as a service)
  application:
    name: CONFIG-SERVER

# Configuration to use centralized configuration (yml) file from Config Server (GitHub)
#  config:
#    import: optional:configserver:http://localhost:8082

# Configuration for config server (github)
  cloud:
    config:
      server:
        git:
          uri: https://github.com/githubashwinchavada2/microservice_config_server
          clone-on-start: true
